name: Branch Protection Status Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  required-checks:
    name: Required Status Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test Suite (Required)
      id: tests
      run: |
        echo "Running comprehensive test suite..."
        npm test
        echo "test_status=passed" >> $GITHUB_OUTPUT
        
    - name: Validation (Required)
      id: validation
      run: |
        echo "Running module validation..."
        npm run validate
        echo "validation_status=passed" >> $GITHUB_OUTPUT
        
    - name: Build Check (Required)
      id: build
      run: |
        echo "Verifying build process..."
        npm run vite:build
        echo "build_status=passed" >> $GITHUB_OUTPUT
        
    - name: Status Summary
      run: |
        echo "## ✅ All Required Checks Passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Results:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Tests: ${{ steps.tests.outputs.test_status }}" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Validation: ${{ steps.validation.outputs.validation_status }}" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Build: ${{ steps.build.outputs.build_status }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**This PR meets all quality requirements and can be merged safely.**" >> $GITHUB_STEP_SUMMARY